### PR TITLE
Added function to get albumcover online.

### PR DESCRIPTION
**Pull request by deepjyoti30**
I could not test it since all the songs i have already have a cover embedded. Please test and merge it if it works otherwise suggest changes.

UPDATE: Tested. Working all right.

#7 Can be closed.

### CODE REVIEW

**Comment by mateossh** [comment]
You should stop using `wget` in downloading cover when you used `curl` before. It just adds more unnecessary dependencies

**Comment by sdushantha** [comment]
@deepjyoti30, I agree with @mateossh that we should use `curl`.

I think this is how it would look like with curl:
`curl -o $COVER deezerAPi.com`

To have no output, you can use the `-s` flag to make `curl` silent
`curl -s -o $COVER deezerAPi.com`

**Comment by sdushantha** [comment]
@deepjyoti30 
Also, it would be nice if you could check if there is an internet connection

```bash
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
    echo "connected to internet :)"
    get_cover_online
else
  echo "no internet connection, using the music note..."
fi
```

**Comment by deepjyoti30** [comment]
@sdushantha Made the changes. Thanks for the suggestions though!

**Comment by sdushantha** [comment]
@deepjyoti30 There seems to be an error on line 1. But line 1 is the shebang..?
```bash
♥ kunst ❯ bash kunst 
kunst: extracted album art
kunst: resized album art to 250x250
kunst: swapped album art to Metallica - Nothing Else Matters
------------------------------------------
kunst: received event from mpd
error: file does not have an album art
parse error: Invalid numeric literal at line 1, column 20
error: Cover not found online
kunst: swapped album art to KONGOS - Come with Me Now
------------------------------------------
kunst: received event from mpd
error: file does not have an album art
parse error: Invalid numeric literal at line 1, column 20
error: Cover not found online
kunst: swapped album art to KONGOS - Come with Me Now
------------------------------------------
```

**Comment by deepjyoti30** [comment]
@sdushantha Weird. I'm not getting any errors. Its working all right for me

**Comment by sdushantha** [comment]
@deepjyoti30 
I understand know, `Invalid numeric literal at line 1, column 20` is from `jq` parsing the JSON data. 
I found what it *could* be;
https://stackoverflow.com/questions/39023953/jq-invalid-numeric-literal-error-with-valid-json-data
https://stackoverflow.com/questions/33352930/jq-issues-with-comments-on-json-file

Not sure how to fix this. :disappointed:

**Comment by sdushantha** [comment]
I can email you the music file which is causing this error.

**Comment by deepjyoti30** [comment]
@sdushantha Okay got it. The code expects that the API returns just one result but in the case of the KONGOS song there's more than one result. Try with other songs. I will try to fix it ASAP.

**Comment by sdushantha** [comment]
Okay, that makes sense 😊
Thanks

**Comment by deepjyoti30** [comment]
@sdushantha Must be fixed now. Please try!

**Comment by deepjyoti30** [comment]
@sdushantha Added commandline arguments to pass dimension or music dir.

**Comment by sdushantha** [comment]
@deepjyoti30  thanks for fixing it and adding the command line arguments! There is one last problem...
If the album cover is not found using the API, it is not showing the music note.

As you can see, it is still showing the art of the previous song and has not changed to the music note
screenshot_19-02-19_at_11-39-30

**Comment by deepjyoti30** [comment]
@sdushantha Should be fixed now.

**Comment by sdushantha** [comment]
@deepjyoti30 thanks, it works perfectly now :)

**Pull request merged**
