### PR TITLE
added capability to write missing song tags

### PR DESCRIPTION
**Pull request by DragonGhost7**
Not much, but now kunst will be able to write missing song tags using eyeD3 and add images if they cant be extracted.

### CODE REVIEW

**Comment by sdushantha** [comment]
Awesome! Does everything work for you? I am not able to test this because all my music are fully tagged.

I will merge this after I get a confirmation from you :+1:

**Comment by DragonGhost7** [comment]
Indeed, all is working, and here is a demo : 

output

(sorry for low quality, need to fit under 10 M)

**Comment by sdushantha** [comment]
From the GIF, I see that the divider lines `------` do not cover the width of the terminal. Could you fix that? If you look through the code, you can I see that I measure the width of the terminal, and then output the divider lines according to the length of the terminal. Just makes it look nicer :)

**Comment by DragonGhost7** [comment]
Im afraid these lines are made by eyeD3, and i dont yet have a solution how to fix it.

**Comment by sdushantha** [comment]
Okay, no problem. We can find a solution later :)

**Pull request merged**
