### PR TITLE
Support `cover.{jpg,png}`.

### LINKED ISSUE #9: Support `cover.{jpg,png}`
Many music organisers store their cover art along the album, instead of embedded inside the file. Typically, this file is called `cover.jpg`.

### PR DESCRIPTION
**Pull request by rubdos**
Fixes #9

Let me know if you want me to somehow refactor this!

### CODE REVIEW

**Comment by sdushantha** [comment]
I did not test it out, but fro reading what you wrote, it looks like it is possible to refractor it. 
If it is possible, try using a while card 
`{*.png, *.jpg}` <--- not sure that is valid

**Comment by rubdos** [comment]
Reason I did not do it is because I *could* change it to `cp --reflink` for `jpg`... Meh, it's okay. Only copies to `/tmp` anyway :-)

**Comment by sdushantha** [comment]
@rubdos Great! 

@gregf Could you test this on your machine? I cant because my music is organized differently :)

I will merge it after @gregf tests it

**Comment by gregf** [comment]
@sdushantha works for me! Ty @rubdos for taking the time to do this.

**Comment by rubdos** [comment]
> @sdushantha works for me! Ty @rubdos for taking the time to do this.

No problem. Next up for me is getting ncmpcpp to start together with kunst; will be nice ! :D

**Pull request merged**
